# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b211dfba441a6b97fbbf607c5a65aa187ecf986aa9beb98ce33b21c1c4421f71fbd6cc3a953566b61b5888aa4f771ec57a612131e341c502c31ebe0a6b0d04cc

test:
  secret_key_base: 3f64bb6bd91cc97f20246a07c06078903b0225b7020b312688e285a4dff5aa7f9b2743c33f1c5e72cfec7c5e7e82eced41728a08ca72577960a22a4e849322cd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
